export default constants = {
  primaryColor: '#C78B9E',
  bannerColor: '#D9D9D9',
  productFont: '',
  productControllTitleColor: '#2',
  productTitleFontColor: '#4A4A4A',
  productDiscFontColor: '#787775',
  productPriceColor: '#2F2F2F',
  productDiscountColor: '#D41111',
  bookmarkRoundColor: '#DCDCDC',
  productTitleFontSize: 9,
  productDiscFontSize: 8,
  productPriceSize: 12,
  productDiscountSize: 12,
  borderWidth: 1,
  borderColor: '#D9D9D9',
  breadcrumFont: 15,
  bredcrumColor: '#787775',
  IndividualProductTitleFontSize: 15,
  IndividualProductTitleFontWeight: '500',
  IndividualProductPriceFontSize: 15,
  IndividualProductPriceFontWeight: '500',
  IndividualProductPriceSecFontSize: 10,
  ColorTitleFont: 18,
  ColorTitleWeight: '500',
  ColorNameFont: 22,
  grey: '#2F2F2F',
  ColorNameColor: '#787775',
  primaryFont: 'Josefin Sans',
};
